// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVt5RjSlIsflJAW_lJcVbXUwUTeAoowWo',
    appId: '1:2907392182:web:e297adf5d51704066abe17',
    messagingSenderId: '2907392182',
    projectId: 'warrior-5f65c',
    authDomain: 'warrior-5f65c.firebaseapp.com',
    databaseURL: 'https://warrior-5f65c.firebaseio.com',
    storageBucket: 'warrior-5f65c.appspot.com',
    measurementId: 'G-TRNWGECMQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_0XFj7HIYB6uOczQHDfvs2s5wSizslJw',
    appId: '1:2907392182:android:97e591f52e4bf6fd6abe17',
    messagingSenderId: '2907392182',
    projectId: 'warrior-5f65c',
    databaseURL: 'https://warrior-5f65c.firebaseio.com',
    storageBucket: 'warrior-5f65c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3B5nPZHLqUoLvGxRrhreLmWiwCjofnCk',
    appId: '1:2907392182:ios:0092334c1f4b528e6abe17',
    messagingSenderId: '2907392182',
    projectId: 'warrior-5f65c',
    databaseURL: 'https://warrior-5f65c.firebaseio.com',
    storageBucket: 'warrior-5f65c.appspot.com',
    androidClientId: '2907392182-6i0h4rhndvatcq17vqcrhvr6c613n9hc.apps.googleusercontent.com',
    iosClientId: '2907392182-7pktj60j5h86ohta2eqtrpchefpvk1kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.gnbTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3B5nPZHLqUoLvGxRrhreLmWiwCjofnCk',
    appId: '1:2907392182:ios:0092334c1f4b528e6abe17',
    messagingSenderId: '2907392182',
    projectId: 'warrior-5f65c',
    databaseURL: 'https://warrior-5f65c.firebaseio.com',
    storageBucket: 'warrior-5f65c.appspot.com',
    androidClientId: '2907392182-6i0h4rhndvatcq17vqcrhvr6c613n9hc.apps.googleusercontent.com',
    iosClientId: '2907392182-7pktj60j5h86ohta2eqtrpchefpvk1kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.gnbTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAnw21BH6BFK4EwB8pIkXxw_7bOR_Odr8',
    appId: '1:2907392182:web:2292c5a4ce4e367c6abe17',
    messagingSenderId: '2907392182',
    projectId: 'warrior-5f65c',
    authDomain: 'warrior-5f65c.firebaseapp.com',
    databaseURL: 'https://warrior-5f65c.firebaseio.com',
    storageBucket: 'warrior-5f65c.appspot.com',
    measurementId: 'G-Y73VSD9EBL',
  );
}
